language: node_js
node_js:
  - "15.11.0"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - dev
    - master
sudo: required
services:
  - docker
before_install:
  - docker build -t dimasokta14/cryptoday -f Dockerfile.dev .
script:
  - docker run -e CI=true dimasokta14/cryptoday npm run test
after_success:
  - docker build -t dimasokta14/cryptoday .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dimasokta14/cryptoday

